package com.fitness.nutritionservice.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.Instant;
import java.time.LocalDateTime;

@Data
@Document(collection = "nutrition_recommendations")
public class NutritionRecommendation {

    @Id
    private String id;
    private String userId;

    // The advice generated by the AI
    private String recommendationText;

    // So you can link it back to the activity that triggered it (optional but useful)
    private String sourceActivityId;

    private LocalDateTime createdAt;

}