spring.datasource.url=jdbc:postgresql://localhost:5432/fitcoredb
spring.datasource.username=fitcore_user
spring.datasource.password=fitcore_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

logging.level.com.fitcore=INFO
