spring.application.name=USER-SERVICE
spring.config.import=optional:configserver:http://localhost:8888

# Gmail SMTP configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=help4finance.app@gmail.com
spring.mail.password=zbgd sglv pjfj okop
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.from=help4finance.app@gmail.com